# Generated by Django 4.1.6 on 2023-02-09 13:15

from django.db import migrations, models
import vacancies.models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancies", "0007_vacancy_min_experience"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="update_at",
            field=models.DateField(
                null=True, validators=[vacancies.models.check_date_not_past]
            ),
        ),
    ]
